=== friodelsol/projekt/API/json-schema/performer-by-id.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string" },
    "country": { "type": "string" },
    "tags": {
      "type": "array",
      "items": { "type": "string" }
    }
  }
}

=== friodelsol/projekt/API/json/performers/p059.json
{
                "id": "p059",
                "name": "Midnight Carousel",
                "country": "United Kingdom",
                "tags": [
                    
                        "Trance",
                        "Progressive House"
                ]
            }
