=== friodelsol/projekt/API/json-schema/venue-by-id.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string" },
    "type": { "type": "string" },
    "capacity": { "type": "integer" },
    "area": { "type": "string" },
    "location": {
      "type": "object",
      "properties": {
        "city": { "type": "string" },
        "postalCode": { "type": "string" },
        "country": { "type": "string" }
      }
    },
    "facilities": {
      "type": "array",
      "items": { "type": "string" }
    }
  }
}

=== friodelsol/projekt/API/json/venues/v2.json
{
                "id": "v2",
                "name": "Underground Stage - Neon Cave",
                "type": "Indoor Stage",
                "capacity": 8000,
                "area": "Holesovice",
                "location": {
                    "city": "Prague",
                    "postalCode": "170 00",
                    "country": "Czech Republic"
                },
                "facilities": [
                    
                        "Bar",
                        "Lockers",
                        "First Aid",
                        "Rest Area"
                ]
            }

=== friodelsol/projekt/API/json/venues/v1.json
{
                "id": "v1",
                "name": "Mainstage - Astral Gate",
                "type": "Outdoor Stage",
                "capacity": 20000,
                "area": "Letna Park",
                "location": {
                    "city": "Prague",
                    "postalCode": "170 00",
                    "country": "Czech Republic"
                },
                "facilities": [
                    
                        "Food Court",
                        "Merch Booth",
                        "First Aid",
                        "Water Refill"
                ]
            }
